package client

import (
	"time"
)

type SeasonClient struct {
	ID        string    `json:"id" bson:"_id,omitempty"`
	TenantID  string    `json:"tenant_id" bson:"tenant_id"`
	PersonID  string    `json:"person_id" bson:"person_id"`
	SeasonID  string    `json:"season_id" bson:"season_id"`
	Dogs      []Dog     `json:"dogs" bson:"dogs"`
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

type Dog struct {
	ID              string  `json:"id" bson:"id"` // Generated by client or backend (e.g. uuid)
	Breed           string  `json:"breed" bson:"breed"`
	Judge           string  `json:"judge" bson:"judge"`
	IsOwner         *bool   `json:"is_owner" bson:"is_owner"`
	CompetitionsWon int     `json:"competitions_won" bson:"competitions_won"`
	Photos          []Photo `json:"photos" bson:"photos"`
}

type Photo struct {
	ID             string   `json:"id" bson:"id"`
	FileNumber     string   `json:"file_number" bson:"file_number"`
	PhotographerID string   `json:"photographer_id" bson:"photographer_id"`
	PaymentMethod  string   `json:"payment_method" bson:"payment_method"` // Pix, Credit Card, Debit Card, Cash, Não pago
	AmountPaid     *float64 `json:"amount_paid" bson:"amount_paid"`
}
